"""implement phase zero data model

Revision ID: 086e30120b92
Revises: 0001_phase_zero_foundation
Create Date: 2026-07-16 15:31:22.900972
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '086e30120b92'
down_revision: str | None = '0001_phase_zero_foundation'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_channels_slug')
    )
    op.create_table('provider_configurations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_provider_configurations_name')
    )
    op.create_table('content_jobs',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('current_state', sa.Enum('DRAFT', 'TOPIC_APPROVED', 'RESEARCHING', 'RESEARCH_REVIEW', 'SCRIPTING', 'SCRIPT_REVIEW', 'SCENE_PLANNING', 'MEDIA_PRODUCTION', 'VOICE_PRODUCTION', 'RENDERING', 'QUALITY_REVIEW', 'AWAITING_APPROVAL', 'APPROVED', 'PUBLISHING', 'PUBLISHED', 'REJECTED', 'FAILED', name='workflow_state'), server_default='DRAFT', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('budget_limit_cents', sa.BigInteger(), nullable=False),
    sa.Column('spent_cents', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget_limit_cents >= 0', name='ck_content_jobs_budget_nonnegative'),
    sa.CheckConstraint('spent_cents >= 0', name='ck_content_jobs_spent_nonnegative'),
    sa.CheckConstraint('version >= 1', name='ck_content_jobs_version_positive'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_jobs_channel_id'), 'content_jobs', ['channel_id'], unique=False)
    op.create_index('ix_content_jobs_state_created', 'content_jobs', ['current_state', 'created_at'], unique=False)
    op.create_table('approval_requests',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_requests_job_status', 'approval_requests', ['job_id', 'status'], unique=False)
    op.create_table('artifacts',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('RESEARCH', 'SCRIPT', 'SCENE_PLAN', 'IMAGE', 'AUDIO', 'VIDEO', 'OTHER', name='artifact_kind'), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_artifacts_size_nonnegative'),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 'object_key', name='uq_artifacts_object')
    )
    op.create_index('ix_artifacts_job_kind', 'artifacts', ['job_id', 'kind'], unique=False)
    op.create_table('audit_events',
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'WORKER', name='actor_type'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_job_created', 'audit_events', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_job_id'), 'audit_events', ['job_id'], unique=False)
    op.create_table('job_tasks',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'RETRY', 'FAILED', name='task_status'), server_default='PENDING', nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=200), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_job_tasks_attempts_nonnegative'),
    sa.CheckConstraint('max_attempts > 0', name='ck_job_tasks_max_attempts_positive'),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_tasks_claim', 'job_tasks', ['status', 'available_at', 'created_at'], unique=False)
    op.create_table('provider_calls',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('provider_configuration_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='provider_call_status'), nullable=False),
    sa.Column('request_reference', sa.String(length=500), nullable=True),
    sa.Column('response_reference', sa.String(length=500), nullable=True),
    sa.Column('cost_cents', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cost_cents >= 0', name='ck_provider_calls_cost_nonnegative'),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_configuration_id'], ['provider_configurations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_calls_job_created', 'provider_calls', ['job_id', 'created_at'], unique=False)
    op.create_table('workflow_transitions',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.Enum('DRAFT', 'TOPIC_APPROVED', 'RESEARCHING', 'RESEARCH_REVIEW', 'SCRIPTING', 'SCRIPT_REVIEW', 'SCENE_PLANNING', 'MEDIA_PRODUCTION', 'VOICE_PRODUCTION', 'RENDERING', 'QUALITY_REVIEW', 'AWAITING_APPROVAL', 'APPROVED', 'PUBLISHING', 'PUBLISHED', 'REJECTED', 'FAILED', name='workflow_state'), nullable=False),
    sa.Column('to_state', sa.Enum('DRAFT', 'TOPIC_APPROVED', 'RESEARCHING', 'RESEARCH_REVIEW', 'SCRIPTING', 'SCRIPT_REVIEW', 'SCENE_PLANNING', 'MEDIA_PRODUCTION', 'VOICE_PRODUCTION', 'RENDERING', 'QUALITY_REVIEW', 'AWAITING_APPROVAL', 'APPROVED', 'PUBLISHING', 'PUBLISHED', 'REJECTED', 'FAILED', name='workflow_state'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'WORKER', name='actor_type'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('job_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_transitions_job_created', 'workflow_transitions', ['job_id', 'created_at'], unique=False)
    op.create_table('cost_entries',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('provider_call_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount_cents >= 0', name='ck_cost_entries_amount_nonnegative'),
    sa.ForeignKeyConstraint(['job_id'], ['content_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_call_id'], ['provider_calls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_entries_job_created', 'cost_entries', ['job_id', 'created_at'], unique=False)
    op.execute(
        """
        CREATE FUNCTION reject_audit_event_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events are immutable';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_events_immutable
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS audit_events_immutable ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS reject_audit_event_mutation()")
    op.drop_index('ix_cost_entries_job_created', table_name='cost_entries')
    op.drop_table('cost_entries')
    op.drop_index('ix_workflow_transitions_job_created', table_name='workflow_transitions')
    op.drop_table('workflow_transitions')
    op.drop_index('ix_provider_calls_job_created', table_name='provider_calls')
    op.drop_table('provider_calls')
    op.drop_index('ix_job_tasks_claim', table_name='job_tasks')
    op.drop_table('job_tasks')
    op.drop_index(op.f('ix_audit_events_job_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_job_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_artifacts_job_kind', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_approval_requests_job_status', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('ix_content_jobs_state_created', table_name='content_jobs')
    op.drop_index(op.f('ix_content_jobs_channel_id'), table_name='content_jobs')
    op.drop_table('content_jobs')
    op.drop_table('provider_configurations')
    op.drop_table('channels')
    # ### end Alembic commands ###
